<a href="https://colab.research.google.com/github/FernandoCasco/Datawarehouse-seguros/blob/main/Clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Repositorio Fernando Casco 25-0359-2022](https://github.com/FernandoCasco/Datawarehouse-seguros.git)

In [1]:
import pandas as pd

In [27]:
url = "https://raw.githubusercontent.com/FernandoCasco/Datawarehouse-seguros/refs/heads/main/data/clientes.csv"

In [28]:
#lectura del archivo
df = pd.read_csv(url)
print("Dataset Cargado Correctamente")

Dataset Cargado Correctamente

In [29]:
display(df.head())

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

BLOQUE 2: Exploración del DATASET

In [34]:
print("Primeras filas del datset")
display(df.head())

Primeras filas del datset

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [36]:
print("Dimensiones del dataset (filas, columnas)")
print(df.shape)

Dimensiones del dataset (filas, columnas)
(3030, 7)

In [35]:
print("Columnas del dataset")
print(df.columns)

Columnas del datset
Index(['id_cliente', 'nombre', 'email', 'genero', 'fecha_nacimiento', 'ciudad',
       'segmento'],
      dtype='object')

In [37]:
print("Tipo de datos")
print(df.dtypes)

Tipo de datos
id_cliente           int64
nombre              object
email               object
genero              object
fecha_nacimiento    object
ciudad              object
segmento            object
dtype: object

In [38]:
print("Valores nulos por columna")
print(df.isnull().sum())

Valores nulos por columna
id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

In [39]:
print("Registros duplicados")
print(df.duplicated().sum())

Registros duplicados
0

BLOQUE 3 : LIMPIEZA DE DATOS

In [40]:
#Elimina espacios al inicio y al final en columnas de texto
for col in df.select_dtypes(include=["object"]).columns:df[col]=df[col].str.strip()

In [44]:
#Normalizar el nombre
df["nombre"]=df["nombre"].str.title()

In [45]:
#Normalizar el email
df["email"]=df["email"].str.lower()

In [46]:
#Normalizar genero
df["genero"]=df["genero"].str.upper()

In [48]:
#Convertir fecha de nacimiento a formato fecha
df['fecha_nacimiento']=pd.to_datetime(df["fecha_nacimiento"],errors="coerce")

In [55]:
#Normalizar ciudad
df["ciudad"]=df["ciudad"].astype(str)
df["ciudad"]=df["ciudad"].str.strip()
df["ciudad"]=df["ciudad"].str.upper()

In [56]:
#Limpieza de segmento
df["segmento"]=df["segmento"].astype(str)
df["segmento"]=df["segmento"].str.strip()
df["segmento"]=df["segmento"].str.upper()

In [57]:
for col in df.columns: print(col)

id_cliente
nombre
email
genero
fecha_nacimiento
ciudad
segmento

BLOQUE 4: VALIDACIÓN DE DATOS

In [59]:
#Crear columna para registrar errores
df["motivo_rechazo"] = ""


#validar id_cliente
df.loc[df["id_cliente"].isnull(), "motivo_rechazo"] = "id_cliente nulo"; ""

''